import itertools

text = "GTCGTCACTGGTCGTCACTGGTCGTCACTGGTCGTCACTGTTCTCATGGTTTCTCATGGTGTCGTCACTGGTCGTCACTGTTCTCATGGTTGCTTCTTTTCCGTCCATGCTTCTTTTTCTCATGGTGTCGTCACTGTTCTCATGGTTCCGTCCATCCGTCCATTCTCATGGTGTCGTCACTGACTCAGCTTTCTCATGGTACTCAGCTACTCAGCTTCCGTCCATCCGTCCATGCTTCTTTTCCGTCCATGCTTCTTTGTCGTCACTGTTCTCATGGTTCCGTCCATTCTCATGGTGTCGTCACTGTGCTTCTTTTGCTTCTTTGTCGTCACTGTCCGTCCATCCGTCCATCCGTCCATGCTTCTTTTCCGTCCATGCTTCTTTTCCGTCCATCCGTCCATGCTTCTTTACTCAGCTGTCGTCACTGGTCGTCACTGACTCAGCTTGCTTCTTTTCCGTCCAACTCAGCTTTCTCATGGTTTCTCATGGTTCCGTCCAACTCAGCTACTCAGCTTCCGTCCAGTCGTCACTGACTCAGCTACTCAGCTGTCGTCACTGTGCTTCTTTGTCGTCACTGTTCTCATGGTTTCTCATGGTTTCTCATGGTACTCAGCTGTCGTCACTGACTCAGCTACTCAGCTACTCAGCTACTCAGCTTCCGTCCATTCTCATGGTGTCGTCACTGGTCGTCACTGGTCGTCACTGTCCGTCCATGCTTCTTTTCCGTCCATGCTTCTTTTCCGTCCAACTCAGCTTCCGTCCATTCTCATGGTACTCAGCTTCCGTCCAGTCGTCACTGTTCTCATGGTACTCAGCTACTCAGCTTCCGTCCATTCTCATGGTTGCTTCTTTTTCTCATGGTTCCGTCCATTCTCATGGTACTCAGCTACTCAGCTGTCGTCACTG"
k = 6
d = 3

allKmeres = [ ''.join(l) for l in itertools.product("ACTG", repeat = k) ]
kmereCounts = {}
count = 0

for allK in allKmeres:
    for window in range(0, len(text) - k + 1):
        count = 0
        for i in range(0 , k):
            if text[window+i] != allK[i]:
                count += 1
            if count > d:
                break
        if count <= d:
            if allK in kmereCounts:
                kmereCounts[allK] += 1
            else:
                kmereCounts[allK] = 1

max = 0
largestK = []

for key, value in kmereCounts.items():
    if value > max:
        max = value
        largestK.clear()
    if value == max:
        largestK.append(key)

parse = " ".join(str(x) for x in largestK)
print(parse) 